LeggedRobotCfg:
  init_state:
    # target angles [rad] when action = 0.0
    default_joint_angle:
      leg_l1_joint: 0.0
      leg_l2_joint: -0.0
      leg_l3_joint: -0.36
      leg_l4_joint: 0.72
      leg_l5_joint: -0.36
      leg_l6_joint: 0
      leg_r1_joint: -0.0
      leg_r2_joint: -0.0
      leg_r3_joint: -0.36
      leg_r4_joint: 0.72
      leg_r5_joint: -0.36
      leg_r6_joint: 0


  control:
    stiffness:
      leg_l1_joint: 120
      leg_l2_joint: 120
      leg_l3_joint: 160
      leg_l4_joint: 160
      leg_l5_joint: 40
      leg_l6_joint: 40
      leg_r1_joint: 120
      leg_r2_joint: 120
      leg_r3_joint: 160
      leg_r4_joint: 160
      leg_r5_joint: 40
      leg_r6_joint: 40
    damping:
      leg_l1_joint: 3
      leg_l2_joint: 3
      leg_l3_joint: 4
      leg_l4_joint: 4
      leg_l5_joint: 1
      leg_l6_joint: 1
      leg_r1_joint: 3
      leg_r2_joint: 3
      leg_r3_joint: 4
      leg_r4_joint: 4
      leg_r5_joint: 1
      leg_r6_joint: 1
    action_scale: 0.5
    decimation: 10
    cycle_time: 0.64

  normalization:    
    clip_scales:
      clip_observations: 100.0
      clip_actions: 100.0
    obs_scales:
      lin_vel: 2.
      ang_vel: 1.
      dof_pos: 1.
      dof_vel: 0.05
      quat: 1.
      height_measurements: 5.0

  size:
    actions_size: 12
    observations_size: 47
